version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.4.0

workflows:
  build:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY
          region: AWS_REGION
          repo: ingestd
          tag: "${CIRCLE_SHA1}"
          path: "confluent-platform/kafka-connect"
