version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.4.0

jobs:
  pull:
    docker:
      - image: confluentinc/cp-kafka-connect-base
  build-image:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            RUN confluent-hub install --no-prompt debezium/debezium-connecter-mysql:0.9.5 \
            && confluent-hub install --no-prompt debezium/debezium-connecter-postgresql:0.9.5 \
            && confluent-hub install --no-prompt confluentinc/kafka-connect-s3-source:1.0.1 \
            && confluent-hub install --no-prompt confluentinc/kafka-connect-avro-converter:5.3.1 \
            && confluent-hub install --no-prompt confluentinc/connect-transforms:1.2.1
workflows:
  build:
    jobs:
      - pull
      - build-image
  aws-ecr/build_and_push_image:
    environment:
      - account-url: AWS_ECR_ACCOUNT_URL
      - aws-access-key-id: ACCESS_KEY_ID
      - aws-secret-access-key: SECRET_ACCESS_KEY
      - region: AWS_REGION
      - repo: ingestd
      - tag: "${CIRCLE_SHA1}"
      - path: "confluent-platform/kafka-connect"


