version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.3.0

workflows:
  build_and_push_image:
    jobs:
      build:
        account-url: AWS_ECR_ACCOUNT_URL
        aws-access-key-id: ACCESS_KEY_ID
        aws-secret-access-key: SECRET_ACCESS_KEY
        region: AWS_REGION
        repo: ingestd
        tag: latest
        dockerfile: Dockerfile
        path: docker/Dockerfile
