version: '1.0'

services:
  zoo:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka100
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 100
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka100:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  schema-registry:
    image: confluentinc/cp-schema-registry
    hostname: schema-registry
    ports:
      - 8081:8081
    depends_on:
      - zookeeper
      - kafka
    environment:
        SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka100:9092
        SCHEMA_REGISTRY_HOST_NAME: schema-registry
        SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zoo:2181

  ksql-server:
    image: confluentinc/cp-ksql-server
      depends_on:
        - kafka
        - schema-registry
      environment:
        KSQL_BOOTSTRAP_SERVERS: PLAINTEXT://kafka100:9092
        KSQL_LISTENERS: http://0.0.0.0:8088
        KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
        KSQL_KSQL_SERVICE_ID: ksql-server

  kafka-connect:
    image: ingestd/cp-connect
